/**
 * License.js — Device activation license
 *
 * Each license key is a one-time-use code generated by admin.
 * Once a device registers with it, the key is bound to that device's MAC address.
 * Any second registration attempt with the same key from a different MAC is rejected.
 */
const mongoose = require("mongoose");
const crypto   = require("crypto");

function generateKey() {
  // Format: EDUC-XXXX-XXXX-XXXX (uppercase alphanumeric, no ambiguous chars)
  const chars  = "ABCDEFGHJKLMNPQRSTUVWXYZ23456789"; // no 0,O,1,I
  const seg    = () => Array.from({ length: 4 }, () => chars[Math.floor(Math.random() * chars.length)]).join("");
  return `EDUC-${seg()}-${seg()}-${seg()}`;
}

const licenseSchema = new mongoose.Schema(
  {
    key: {
      type:     String,
      required: true,
      unique:   true,
      default:  generateKey,
      uppercase: true,
      trim:     true,
    },
    // Admin-assigned label so they know which room/device it's for
    label: { type: String, default: "" },

    // Activation state
    isActivated:  { type: Boolean, default: false },
    activatedAt:  { type: Date },

    // Bound device info (filled on first use)
    deviceMac:    { type: String, default: "" },
    deviceId:     { type: String, default: "" },  // ClassroomDevice._id
    deviceModel:  { type: String, default: "" },
    roomNumber:   { type: String, default: "" },
    campus:       { type: String, default: "" },
    block:        { type: String, default: "" },

    // Who generated this license
    createdBy:    { type: mongoose.Schema.Types.ObjectId, ref: "LCS_User" },

    // Optional expiry (null = never expires)
    expiresAt:    { type: Date, default: null },

    isActive:     { type: Boolean, default: true },
  },
  { timestamps: true }
);

module.exports = mongoose.model("LCS_License", licenseSchema);
